### ISSUE TITLE
Output from forward in `test_reverse` has crazy size

### ISSUE THREAD

**Issue by kshyatt** [EnzymeAD/Enzyme.jl#2846]
https://github.com/QuantumKitHub/MatrixAlgebraKit.jl/pull/86 for a reproducer

From within my `augmented_primal` function, right before it returns:
```
size.(primal) = ((19, 17), (17, 17), (17, 17), (1,))
```

From within `test_reverse`, after the `forward` from `autodiff_thunk` is run:
```
size.(y_ad) = ((19, 17), (1, 1), (17, 4818589264), (17,))
```

IDK what happened here but it looks like very bad things are happening to memory layout

**Comment by kshyatt** [comment]
OK some further testing seems to show this is only happening on 1.12, on 1.11 Enzyme correctly flagged the actual problem in my rule

**Comment by wsmoses** [comment]
A related cause of issues on 1.12 has been resolved, can you check if this still errs?

**Comment by wsmoses** [comment]
Is this still an issue?

**Comment by kshyatt** [comment]
I think not

**Comment by kshyatt** [comment]
Oh nope I am still seeing this, I'll try again to make a MWE...

**Comment by kshyatt** [comment]
The underlying rule seems to work because I don't see any problems on 1.10...

**Comment by wsmoses** [comment]
can you retry on latest? I think that should fix some rule related errors
